///////////////////////////////////////////////////////////
//  UIListener.cs
//  Implementation of the Class UIListener
//  Generated by Enterprise Architect
//  Created on:      02-2月-2021 16:07:33
//  Original author: hebin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using gf;

namespace GForce
{
    public abstract class UIListener
    {
        /// 
        /// <param name="device"></param>
        public abstract void onDeviceConnected(Device device);


        /// 
        /// <param name="device"></param>
        public abstract void onDeviceDiscard(Device device);


        /// 
        /// <param name="device"></param>
        /// <param name="reason"></param>
        public abstract void onDeviceDisconnected(Device device, int reason);


        /// 
        /// <param name="device"></param>
        public abstract void onDeviceFound(Device device);


        public abstract void onScanFinished();


        /// 
        /// <param name="state"></param>
        public abstract void onStateChanged(Hub.HubState state);

        /// 
        /// <param name="device"></param>
        /// <param name="status"></param>
        public abstract void onDeviceStatusChanged(Device device, Device.Status status);

    }//end UIListener

}//end namespace GameCtrler